#!/bin/bash

USER=$1

if [ -z $USER ]; then
	echo "Error: no user name provided"
	exit 1
fi

getent passwd $USER &> /dev/null

if [ $? -ne 0 ]; then
	echo "Error: user '$USER' does not exist"
	exit 1
fi

who | grep $USER &> /dev/null

if [ $? -ne 0 ]; then
	echo "Error: the '$USER' is not logged in"
	exit 1
fi

if [ "$(whoami)" != "root" ]; then
	echo "Error: permission denied"
	exit 1
fi

kill $(pgrep -u $USER) &> /dev/null
userdel -r $USER &> /dev/null

getent passwd $USER &> /dev/null

if [ $? -eq 0 ]; then
	echo "Error: could not delete active user '$USER'"
	exit 1
else
	echo "Successfully deleted active user '$USER'"
fi
